FROM python:3.8

# set the working directory
WORKDIR /app

# install dependencies

COPY requirements.txt /app
RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r requirements.txt --target=/app/appRequirements
ENV PYTHONPATH=/app/appRequirements

RUN apt-get update && apt-get -y install cron
RUN apt-get update && apt-get -y install ffmpeg

# copy the scripts to the folder
COPY ../app/* /app

# Give execution rights on the cron scripts
RUN chmod +x /app/main.py

ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ARG audioPath
ARG textPath
ARG dataPath
ARG wavPath
ARG processedAudioPath
ARG openai_api_key
ARG NotionDB
ARG Notion_secret

ENV audioPath ${audioPath}
ENV textPath ${textPath}
ENV dataPath ${dataPath}
ENV wavPath ${wavPath}
ENV processedAudioPath ${processedAudioPath}
ENV openai_api_key ${openai_api_key}
ENV NotionDB ${NotionDB}
ENV Notion_secret ${Notion_secret}



# Adding crontab to the appropiate location
ADD crontab /etc/cron.d/my-cron-file

# Giving executable permission to crontab file
RUN chmod 0644 /etc/cron.d/my-cron-file

# Running crontab
RUN crontab /etc/cron.d/my-cron-file

# Creating entry point for cron 
ENTRYPOINT ["cron", "-f"]


